CREATE TABLE IF NOT EXISTS logs_API (
    id_log BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    description TEXT NOT NULL,
    ia_response TEXT,
    date_creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);